### ISSUE TITLE
Return Promise<something useful> in cancel/new/updateOffer

### ISSUE THREAD

**Issue by adhusson** [mangrovedao/mangrove#84] opened 2021-12-16 13:59 UTC
We return offer ids on new offer, but we should also return the tx that was mined for all 3 calls.

**Comment by espendk** [comment] 2022-02-20 16:54
@akettal This is a duplicate of #173, right ?

**Comment by espendk** [comment] 2022-03-04 11:10
Closing this as a duplicate of #173

**Closed by espendk** 2022-03-04 11:10 UTC
Labels: duplicate
