### ISSUE TITLE
`newAsk()` hangs on local node forking testnet

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove#164] opened 2022-01-23 11:41 UTC
To reproduce:

1/ set the `chainId` of hardhat network to mumbai -- 80001
2/ on terminal #1 run:
 ```
 npx hardhat node --fork https://polygon-mumbai.g.alchemy.com/v2/xxx --no-deploy
```
3/ on terminal #2 in a `sandbox` folder containing a local install of `ethers.js` and a `.env` with the secrets run a node terminal with the following instructions:
```
> const env = require("dotenv").config();
> const { Mangrove } = require("../mangrove/packages/mangrove.js");
> const ethers = require("ethers");
> let provider = new ethers.providers.WebSocketProvider(
...   env.parsed.MUMBAI_NODE_URL
... );
> let wallet = new ethers.Wallet(env.parsed.MUMBAI_TESTER_PRIVATE_KEY, provider);
> //connecting the API to Mangrove
> let mgv = await Mangrove.connect({ signer: wallet });
> //connecting mgv to a market
> let market = await mgv.market({ base: "DAI", quote: "USDC" });
> // create a simple LP on `market`
> let directLP = await mgv.liquidityProvider(market);
> let prov = await directLP.computeAskProvision();
> tx = await directLP.fundMangrove(prov);
> await tx.wait();
> const { id: ofrId } = await directLP.newAsk({ wants: 105, gives: 104 });
```

Now if you just do 3 (w/o the local node running) everything works fine (although the ask takes a while to pass).

**Comment by espendk** [comment] 2022-01-24 10:21
To ease reproduction (at least for me :-) here are code listings that can be copy-pasted:

```shell
# console #1
DEBUG=* npx hardhat node --fork https://polygon-mumbai.g.alchemy.com/v2/<key> --fork-block-number 24211109 --no-deploy  --hostname 127.0.0.1
```

```shell
# console #2
export MUMBAI_NODE_URL=http://127.0.0.1:8545/
export MUMBAI_TESTER_PRIVATE_KEY=0x...
node
```

```javascript
// Code to paste into console #2 
const { Mangrove } = require(".");
const ethers = require("ethers");
let provider = new ethers.providers.WebSocketProvider(process.env["MUMBAI_NODE_URL"]);
let wallet = new ethers.Wallet(process.env["MUMBAI_TESTER_PRIVATE_KEY"], provider);
let mgv = await Mangrove.connect({ signer: wallet });
let market = await mgv.market({ base: "DAI", quote: "USDC" });
let directLP = await mgv.liquidityProvider(market);
let prov = await directLP.computeAskProvision();
tx = await directLP.fundMangrove(prov);
```

**Comment by jkrivine** [comment] 2022-02-22 15:07
I think this problem occurs when the market is big. It takes too long to discover where the offer should be inserted even if the offer is the best of the book

**Comment by adhusson** [comment] 2022-05-13 11:57
Can you @jkrivine or @espendk reproduce this?

**Comment by espendk** [comment] 2022-05-17 13:12
> Can you @jkrivine or @espendk reproduce this?

I couldn't reproduce a hang, but I got an error that doesn't look good:

```
> const { id: ofrId } = await directLP.newAsk({ wants: 105, gives: 104 });
Uncaught { revert: false, exception: 'tx mined but filter never returned true' }
```

I had to make some small adjustments to the reproduction steps above, so here are the updated steps:

1. Run the following command in one console:
```shell
# Console 1
HARDHAT_NETWORK_CHAIN_ID=80001 DEBUG=* npx hardhat node --fork https://polygon-mumbai.g.alchemy.com/v2/<API-key> --no-deploy  --hostname 127.0.0.1
```

2. In another console, run a node REPL:
```shell
# Console 2
export MUMBAI_NODE_URL=http://127.0.0.1:8545/
export MUMBAI_TESTER_PRIVATE_KEY=0x...
node
```

3. Paste the following code into the REPL in console 2:
```js
// Code to paste into console #2 
const { Mangrove } = require(".");
const ethers = require("ethers");
let provider = new ethers.providers.WebSocketProvider(process.env["MUMBAI_NODE_URL"]);
let wallet = new ethers.Wallet(process.env["MUMBAI_TESTER_PRIVATE_KEY"], provider);
let mgv = await Mangrove.connect({ signer: wallet });
let market = await mgv.market({ base: "DAI", quote: "USDC" });
let directLP = await mgv.liquidityProvider(market);
let prov = await directLP.computeAskProvision();
tx = await directLP.fundMangrove(prov);
await tx.wait();
const { id: ofrId } = await directLP.newAsk({ wants: 105, gives: 104 });
```

**Comment by adhusson** [comment] 2022-05-17 18:37
On my end after adding `bookOptions:{maxOffers:100}` to the params of `mangrove.market`, I get no error.

With the default `maxOffers`, `liquidityProvider.ts` cannot read the offer info it needs and I get
```
/Users/ah/Projects/mangrove/packages/mangrove.js/dist/nodejs/liquidityProvider.js:132
                    id: cbArg.offer.id,
                                    ^

TypeError: Cannot read properties of undefined (reading 'id')
```

**Comment by espendk** [comment] 2022-05-18 09:00
> On my end after adding `bookOptions:{maxOffers:100}` to the params of `mangrove.market`, I get no error.
> 
> With the default `maxOffers`, `liquidityProvider.ts` cannot read the offer info it needs and I get
> 
> ```
> /Users/ah/Projects/mangrove/packages/mangrove.js/dist/nodejs/liquidityProvider.js:132
>                     id: cbArg.offer.id,
>                                     ^
> 
> TypeError: Cannot read properties of undefined (reading 'id')
> ```

Weird that you get a different error. I tested on `master`, commit bdfaad2a9c89ebf07c1bf65364ed8c7d4e49b88a.
How did you use trigger the error? The reproduction steps I posted yesterday?

Re. the error you got, my understanding is that the cache is full and that the offer in question is therefore not cached wherefore `cbArg.offer` isn't set (as documented on `Market.BookSubscriptionCbArgument`). But `liquidityProvider` wrongly assumes the optional `offer` field will contain a value (I’m surprised the type checker isn’t complaining!).

I think an easy and reasonable fix here is to add `offerId` to `Market.BookSubscriptionCbArgument`, I think that'll always be available regardless of whether the offer is in the cache.

**Comment by adhusson** [comment] 2022-05-18 09:33
Checking out bdfaad2a9c89ebf07c1bf65364ed8c7d4e49b88a, I get the same behavior (by using the reproduction steps you posted yesterday), that is: missing `cbArg.offer.id` with default cache size, all good with `maxOffers:100`. I run

```
HARDHAT_NETWORK_CHAIN_ID=80001 DEBUG=* npx hardhat node --fork https://polygon-mumbai.g.alchemy.com/v2/<my-key> --no-deploy  --hostname 127.0.0.1
```

in `./mangrove-solidity`, and I have a file `mangrove.js/repro.js`:

```
const MUMBAI_NODE_URL="http://127.0.0.1:8545/"
const MUMBAI_TESTER_PRIVATE_KEY="<my-private-key>"

const main = async () => {
console.log("start");

const { Mangrove } = require("./dist/nodejs/");
const ethers = require("ethers");
let provider = new ethers.providers.JsonRpcProvider(MUMBAI_NODE_URL);
let wallet = new ethers.Wallet(MUMBAI_TESTER_PRIVATE_KEY, provider);
let mgv = await Mangrove.connect({ signer: wallet });
let market = await mgv.market({ base: "DAI", quote: "USDC",bookOptions:{maxOffers:50} });
let directLP = await mgv.liquidityProvider(market);
let prov = await directLP.computeAskProvision();
tx = await directLP.fundMangrove(prov);
await tx.wait();
const { id: ofrId } = await directLP.newAsk({ wants: 105, gives: 104 });
};

main().then(() => { process.exit(0); }).catch(e => { console.error(e); process.exit(1); });
```

**Comment by adhusson** [comment] 2022-05-18 15:45
Just retried with the fixes merged, still no error. I ran `yarn clean` before.

The error you mention (`tx mined but filter never returned true`) means that the call by `liquidityProvider` 1) did not end in a revert but 2) did not log an `OfferWrite`. 

My understanding of `liquidityProvider` (paging @jkrivine for confirmation) is that during your repro steps, `directLP.mgv.contract.newOffer` is called which is a little worrying since Mangrove's contract should definitely either log `OfferWrite` or revert.

**Comment by espendk** [comment] 2022-05-23 13:44
I've discovered a problem that occurs in the following lines in `Semibook`:

```javascript
      const logs = await this.market.mgv._provider.getLogs({
        fromBlock: blockNumber,
        toBlock: blockNumber,
        ...this.#eventFilter,
      });
```

Sometimes, `getLogs` returns logs for block `blockNumber - 1` and thus the events for block `blockNumber` are never processed. This can be an issue with both ethers.js and Hardhat.

We've seen other issues which could stem from this:
- #205 
- #197 

Once we've fixed the issue here, we should check if those other issues have been fixed as well.

**Comment by espendk** [comment] 2022-05-23 14:03
@adhusson  I just realized that you've been using slightly different code when reproducing: You're using `JsonRpcProvider` instead of the `WebSocketProvider`.

Could you try using the exact code I posted May 17 and see if you get the problem? https://github.com/mangrovedao/mangrove/issues/164#issuecomment-1128852373

**Comment by espendk** [comment] 2022-05-23 14:13
When I use `JsonRpcProvider`, the code works as expected. So the issue seems to be with the `WebSocketProvider` in ethers.js.

**Comment by espendk** [comment] 2022-05-23 14:51
I'm closing this issue and keeping #197 which is specific for the `WebSocketProvider` issue that has turned out to be the root cause here.

**Closed by espendk** 2022-05-23 14:51 UTC
Labels: bug
