### ISSUE TITLE
Market order went wrong even if the tx succeed

### ISSUE THREAD

**Issue by johanleroch** [mangrovedao/mangrove#256] opened 2022-03-17 10:19 UTC
**Describe the bug**
When making a successful tx, I got the "market order went wrong" error message from the mangrove.js library. (So the UI can't show relevant information about the tx to the user).

**To Reproduce**
1. Make a tx on the market WETH-USDC
2. Buy 0.01WETH
3. You'll get an error EVEN if the tx is a success on polygonscan

**Expected behavior**
I expect to not have an error and get the result of the successful tx

**Screenshots**
![image](https://user-images.githubusercontent.com/7213352/158788128-acc83ea8-e9db-4861-8895-0deb8a3c9d12.png)
![image](https://user-images.githubusercontent.com/7213352/158788161-38c763a7-835a-4da0-8db4-74d94b902c04.png)

**Additional context**
It seems that the receipt of a marketOrder doesn't contain events (market.ts line 579)
Reproduced on mangrove.js 0.3.3 and 0.3.4 (can't test 0.3.0 to 0.3.2 cause the library breaks the front on those versions)

**Comment by adhusson** [comment] 2022-03-17 17:15
Issue is due to `taker` argument of `OrderComplete` event now being indexed. Mangrove on mumbai should be redeployed.

**Comment by espendk** [comment] 2022-03-17 19:39
Just so I'm sure I understand: `mangrove.js` is using the ABI's of a newer version of Mangrove than the one that is currently in use and therefore `ethers.js` (used by `mangrove.js`) fails to recognise the `OrderComplete` event - is that right?

If so, the root cause here is that we have contract code on `master` that doesn't match the deployed version.
Maybe we can add a check to CI that verifies that the ABI's on the block explorer matches those in `mangrove.js` ?

**Comment by adhusson** [comment] 2022-03-18 16:48
That's correct -- mangrove.js is using the wrong ABI. We may want a check but it seems fairly difficult to implement. Alternatively commits that change the ABI could trigger a "redeploy Mangrove please" reminder.

**Comment by espendk** [comment] 2022-03-21 08:22
I think the check wouldn't be too difficult:
- The ABI's contained in mangrove.js can be fetched from GitHub, eg https://raw.githubusercontent.com/mangrovedao/mangrove/master/packages/mangrove.js/src/abis/Mangrove.json
- The ABI for the verified contract can be fetched from PolygonScan using their API: https://docs.polygonscan.com/api-endpoints/contracts#get-contract-abi-for-verified-contract-source-codes
- Comparing the ABI's can probably be done using something like `fast-equals` or `lodash`.

**Comment by espendk** [comment] 2022-03-21 08:43
I created an issue for adding a CI check here: #259

It can be done event simpler than I sketched above: We can simply compare the ABI json files in `mangrove-solidity/deployments` and `mangrove.js/src/abis` folders.

**Comment by espendk** [comment] 2022-03-28 07:56
@johanleroch @adhusson  As I understand it, this has been fixed, so I'm closing. Feel free to reopen if I've misunderstood :-)

**Closed by espendk** 2022-03-28 07:56 UTC
Labels: bug
